with open('src/components/Checkout.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { createBooking, downloadPDF } from ' + chr(39) + '../api' + chr(39) + ';\n'
'import { User, CreditCard, Download, CheckCircle } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'\n'
'export default function Checkout({ schedule, seat, onBack }) {\n'
'  const [form, setForm] = useState({ passenger_name: ' + chr(39) + chr(39) + ', passenger_ci: ' + chr(39) + chr(39) + ' });\n'
'  const [booking, setBooking] = useState(null);\n'
'  const [loading, setLoading] = useState(false);\n'
'  const [error, setError] = useState(' + chr(39) + chr(39) + ');\n'
'  const [step, setStep] = useState(1);\n'
'\n'
'  const price = schedule.bus_type === ' + chr(39) + 'cama' + chr(39) + ' ? schedule.price_cama : schedule.bus_type === ' + chr(39) + 'semicama' + chr(39) + ' ? schedule.price_semicama : schedule.price_normal;\n'
'  const total = price + schedule.terminal_fee;\n'
'\n'
'  const handleBook = async () => {\n'
'    if (!form.passenger_name || !form.passenger_ci) { setError(' + chr(39) + 'Completa todos los campos' + chr(39) + '); return; }\n'
'    setLoading(true); setError(' + chr(39) + chr(39) + ');\n'
'    try {\n'
'      const res = await createBooking({ schedule_id: schedule.id, seat_id: seat.id, ...form });\n'
'      setBooking(res.data);\n'
'      setStep(3);\n'
'    } catch (e) { setError(e.response?.data?.detail || ' + chr(39) + 'Error al reservar' + chr(39) + '); }\n'
'    finally { setLoading(false); }\n'
'  };\n'
'\n'
'  const handleDownload = async () => {\n'
'    try {\n'
'      const res = await downloadPDF(booking.id);\n'
'      const url = URL.createObjectURL(new Blob([res.data], { type: ' + chr(39) + 'application/pdf' + chr(39) + ' }));\n'
'      const a = document.createElement(' + chr(39) + 'a' + chr(39) + ');\n'
'      a.href = url; a.download = ' + chr(34) + 'ticket_boliviabus.pdf' + chr(34) + '; a.click();\n'
'    } catch { alert(' + chr(39) + 'Error al descargar PDF' + chr(39) + '); }\n'
'  };\n'
'\n'
'  if (step === 3 && booking) return (\n'
'    <div className=' + chr(34) + 'max-w-lg mx-auto px-4 py-8 text-center' + chr(34) + '>\n'
'      <div className=' + chr(34) + 'card' + chr(34) + '>\n'
'        <CheckCircle size={64} className=' + chr(34) + 'text-green-500 mx-auto mb-4' + chr(34) + '/>\n'
'        <h2 className=' + chr(34) + 'text-2xl font-bold text-[#1B2A6B] mb-2' + chr(34) + '>¡Reserva Confirmada!</h2>\n'
'        <p className=' + chr(34) + 'text-gray-600 mb-4' + chr(34) + '>Tu pasaje ha sido generado exitosamente</p>\n'
'        <div className=' + chr(34) + 'bg-[#f0f4ff] rounded-xl p-4 text-left mb-6' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Pasajero</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>{booking.passenger_name}</span></div>\n'
'          <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Asiento</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>{seat.seat_number} - Piso {seat.floor}</span></div>\n'
'          <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Precio</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>Bs. {booking.base_price}</span></div>\n'
'          <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Terminal</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>Bs. {booking.terminal_fee}</span></div>\n'
'          <div className=' + chr(34) + 'flex justify-between py-2' + chr(34) + '><span className=' + chr(34) + 'font-bold text-[#1B2A6B]' + chr(34) + '>TOTAL</span><span className=' + chr(34) + 'font-bold text-[#1B2A6B] text-lg' + chr(34) + '>Bs. {booking.total_price}</span></div>\n'
'        </div>\n'
'        <button onClick={handleDownload} className=' + chr(34) + 'btn-primary w-full flex items-center justify-center gap-2' + chr(34) + '>\n'
'          <Download size={18}/> Descargar Ticket PDF\n'
'        </button>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'max-w-lg mx-auto px-4 py-8' + chr(34) + '>\n'
'      <button onClick={onBack} className=' + chr(34) + 'text-[#1B2A6B] mb-4 flex items-center gap-1 hover:underline' + chr(34) + '>← Volver</button>\n'
'      <div className=' + chr(34) + 'card' + chr(34) + '>\n'
'        <h3 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B] mb-6 flex items-center gap-2' + chr(34) + '><CreditCard size={22}/> Datos del Pasajero</h3>\n'
'        <div className=' + chr(34) + 'bg-[#f0f4ff] rounded-xl p-4 mb-6' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'grid grid-cols-2 gap-3 text-sm' + chr(34) + '>\n'
'            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Ruta:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>{schedule.origin} → {schedule.destination}</p></div>\n'
'            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Asiento:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>{seat.seat_number} Piso {seat.floor}</p></div>\n'
'            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Precio:</span><p className=' + chr(34) + 'font-bold text-[#1B2A6B]' + chr(34) + '>Bs. {total.toFixed(2)}</p></div>\n'
'            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Tipo:</span><p className=' + chr(34) + 'font-semibold capitalize' + chr(34) + '>{schedule.bus_type}</p></div>\n'
'          </div>\n'
'        </div>\n'
'        <div className=' + chr(34) + 'flex flex-col gap-4' + chr(34) + '>\n'
'          <div>\n'
'            <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1 flex items-center gap-1' + chr(34) + '><User size={14}/> Nombre completo</label>\n'
'            <input className=' + chr(34) + 'input-field' + chr(34) + ' placeholder=' + chr(34) + 'Ej: Juan Carlos Quispe' + chr(34) + ' value={form.passenger_name} onChange={e=>setForm({...form,passenger_name:e.target.value})}/>\n'
'          </div>\n'
'          <div>\n'
'            <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1' + chr(34) + '>CI (con extensión)</label>\n'
'            <input className=' + chr(34) + 'input-field' + chr(34) + ' placeholder=' + chr(34) + 'Ej: 1234567 LP' + chr(34) + ' value={form.passenger_ci} onChange={e=>setForm({...form,passenger_ci:e.target.value})}/>\n'
'          </div>\n'
'        </div>\n'
'        {error && <p className=' + chr(34) + 'text-red-500 text-sm mt-3' + chr(34) + '>{error}</p>}\n'
'        <button onClick={handleBook} disabled={loading} className=' + chr(34) + 'btn-primary w-full mt-6 flex items-center justify-center gap-2' + chr(34) + '>\n'
'          {loading ? ' + chr(39) + 'Procesando...' + chr(39) + ' : ' + chr(39) + '✅ Confirmar Reserva' + chr(39) + '}\n'
'        </button>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: Checkout.jsx')