with open('src/components/MyTrips.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { motion, AnimatePresence } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { Ticket, Download, Share2, MapPin, Clock, RefreshCw } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        'import { useStore } from ' + chr(39) + '../store' + chr(39) + ';',
        'import { downloadPDF } from ' + chr(39) + '../api' + chr(39) + ';',
        '',
        'export default function MyTrips({ onSearch }) {',
        '  const { bookings } = useStore();',
        '',
        '  const handleDownload = async (bookingId) => {',
        '    try {',
        '      const res = await downloadPDF(bookingId);',
        '      const url = URL.createObjectURL(new Blob([res.data], { type: "application/pdf" }));',
        '      const a = document.createElement("a");',
        '      a.href = url; a.download = "ticket_boliviabus.pdf"; a.click();',
        '    } catch { alert("Error al descargar"); }',
        '  };',
        '',
        '  const handleWhatsApp = (booking) => {',
        '    const msg = encodeURIComponent(',
        '      "🚌 *Bolivia Bus — Mi Ticket*\\n\\n" +',
        '      "Pasajero: " + booking.passenger_name + "\\n" +',
        '      "Ruta: " + booking.origin + " → " + booking.destination + "\\n" +',
        '      "Asiento: " + booking.seat_number + "\\n" +',
        '      "Total: Bs. " + booking.total_price + "\\n\\n" +',
        '      "Descarga tu ticket en: http://boliviabus.bo/ticket/" + booking.id',
        '    );',
        '    window.open("https://wa.me/?text=" + msg, "_blank");',
        '  };',
        '',
        '  if (bookings.length === 0) return (',
        '    <div className="max-w-2xl mx-auto px-4 py-16 text-center">',
        '      <motion.div initial={{opacity:0,scale:0.9}} animate={{opacity:1,scale:1}}>',
        '        <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">',
        '          <Ticket size={40} className="text-gray-300"/>',
        '        </div>',
        '        <h3 className="text-xl font-bold text-gray-700 mb-2">No tienes viajes aun</h3>',
        '        <p className="text-gray-400 mb-6">Tus tickets aparecaran aqui despues de comprar</p>',
        '        <button onClick={onSearch} className="btn-primary flex items-center gap-2 mx-auto">',
        '          <MapPin size={16}/> Buscar mi primer viaje',
        '        </button>',
        '      </motion.div>',
        '    </div>',
        '  );',
        '',
        '  return (',
        '    <div className="max-w-2xl mx-auto px-4 py-8">',
        '      <div className="flex items-center justify-between mb-6">',
        '        <h2 className="text-2xl font-black text-[#1B2A6B]">Mis Viajes</h2>',
        '        <span className="bg-[#1B2A6B] text-white text-xs px-3 py-1 rounded-full font-bold">{bookings.length} ticket{bookings.length!==1?"s":""}</span>',
        '      </div>',
        '      <div className="flex flex-col gap-4">',
        '        <AnimatePresence>',
        '          {bookings.map((b, i) => (',
        '            <motion.div key={b.id || i}',
        '              initial={{opacity:0,x:-20}} animate={{opacity:1,x:0}} transition={{delay:i*0.1}}',
        '              className="bg-white rounded-2xl shadow-md border border-gray-100 overflow-hidden">',
        '              <div className="bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] px-5 py-3 flex items-center justify-between">',
        '                <div>',
        '                  <p className="text-white font-bold text-sm">{b.origin || "?"} → {b.destination || "?"}</p>',
        '                  <p className="text-blue-300 text-xs">{b.savedAt ? new Date(b.savedAt).toLocaleDateString("es-BO") : "Reciente"}</p>',
        '                </div>',
        '                <span className={"text-xs px-2 py-1 rounded-full font-bold " + (b.status === "confirmed" ? "bg-green-500 text-white" : "bg-amber-500 text-white")}>',
        '                  {b.status === "confirmed" ? "✅ Confirmado" : b.status}',
        '                </span>',
        '              </div>',
        '              <div className="p-5">',
        '                <div className="grid grid-cols-2 gap-3 text-sm mb-4">',
        '                  <div><span className="text-gray-400">Pasajero</span><p className="font-semibold">{b.passenger_name}</p></div>',
        '                  <div><span className="text-gray-400">Asiento</span><p className="font-semibold">{b.seat_number || "-"}</p></div>',
        '                  <div><span className="text-gray-400">Total pagado</span><p className="font-bold text-[#1B2A6B]">Bs. {b.total_price}</p></div>',
        '                  <div><span className="text-gray-400">Empresa</span><p className="font-semibold">{b.company || "-"}</p></div>',
        '                </div>',
        '                <div className="flex gap-2">',
        '                  <button onClick={() => handleDownload(b.id)}',
        '                    className="flex-1 flex items-center justify-center gap-1 bg-[#1B2A6B] text-white text-sm py-2 rounded-xl font-semibold hover:bg-[#162259] transition-all">',
        '                    <Download size={14}/> PDF',
        '                  </button>',
        '                  <button onClick={() => handleWhatsApp(b)}',
        '                    className="flex-1 flex items-center justify-center gap-1 bg-green-500 text-white text-sm py-2 rounded-xl font-semibold hover:bg-green-600 transition-all">',
        '                    <Share2 size={14}/> WhatsApp',
        '                  </button>',
        '                  <button onClick={onSearch}',
        '                    className="flex items-center justify-center gap-1 border-2 border-[#1B2A6B] text-[#1B2A6B] text-sm px-3 py-2 rounded-xl font-semibold hover:bg-[#1B2A6B] hover:text-white transition-all">',
        '                    <RefreshCw size={14}/> Repetir',
        '                  </button>',
        '                </div>',
        '              </div>',
        '            </motion.div>',
        '          ))}',
        '        </AnimatePresence>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: MyTrips.jsx')