with open('src/components/SeatTimer.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { motion } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { Clock, AlertTriangle } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        '',
        'export default function SeatTimer({ onExpire }) {',
        '  const [seconds, setSeconds] = useState(15 * 60);',
        '',
        '  useEffect(() => {',
        '    const interval = setInterval(() => {',
        '      setSeconds(s => {',
        '        if (s <= 1) { clearInterval(interval); onExpire && onExpire(); return 0; }',
        '        return s - 1;',
        '      });',
        '    }, 1000);',
        '    return () => clearInterval(interval);',
        '  }, []);',
        '',
        '  const mins = Math.floor(seconds / 60);',
        '  const secs = seconds % 60;',
        '  const pct = (seconds / (15 * 60)) * 100;',
        '  const isWarning = seconds < 180;',
        '  const isDanger = seconds < 60;',
        '',
        '  return (',
        '    <motion.div initial={{opacity:0, y:-10}} animate={{opacity:1, y:0}}',
        '      className={"rounded-2xl p-4 mb-4 border-2 " + (isDanger ? "bg-red-50 border-red-400" : isWarning ? "bg-amber-50 border-amber-400" : "bg-blue-50 border-[#1B2A6B]")}>',
        '      <div className="flex items-center justify-between mb-2">',
        '        <div className="flex items-center gap-2">',
        '          {isDanger ? <AlertTriangle size={18} className="text-red-500 animate-bounce"/> : <Clock size={18} className="text-[#1B2A6B]"/>}',
        '          <span className={"text-sm font-bold " + (isDanger ? "text-red-600" : isWarning ? "text-amber-600" : "text-[#1B2A6B]")}>',
        '            {isDanger ? "Tiempo casi agotado!" : isWarning ? "Apurate, poco tiempo!" : "Asiento reservado temporalmente"}',
        '          </span>',
        '        </div>',
        '        <motion.span',
        '          animate={isDanger ? { scale: [1, 1.1, 1] } : {}}',
        '          transition={{ repeat: Infinity, duration: 0.5 }}',
        '          className={"text-2xl font-black font-mono " + (isDanger ? "text-red-600" : isWarning ? "text-amber-600" : "text-[#1B2A6B]")}>',
        '          {String(mins).padStart(2,"0")}:{String(secs).padStart(2,"0")}',
        '        </motion.span>',
        '      </div>',
        '      <div className="w-full bg-gray-200 rounded-full h-2">',
        '        <motion.div',
        '          className={"h-2 rounded-full " + (isDanger ? "bg-red-500" : isWarning ? "bg-amber-500" : "bg-[#1B2A6B]")}',
        '          style={{ width: pct + "%" }}',
        '          transition={{ duration: 0.5 }}/>',
        '      </div>',
        '      <p className="text-xs text-gray-500 mt-1 text-center">El asiento se liberara automaticamente si no completas la compra</p>',
        '    </motion.div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: SeatTimer.jsx')