with open('src/components/SeatMap.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { motion, AnimatePresence } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { getSeatMap } from ' + chr(39) + '../api' + chr(39) + ';',
        'import SeatTimer from ' + chr(39) + './SeatTimer' + chr(39) + ';',
        'import { Star, Armchair } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        '',
        'const STATUS_CONFIG = {',
        '  available: { bg: "bg-white",        border: "border-[#1B2A6B]", text: "text-[#1B2A6B]", hover: "hover:bg-[#1B2A6B] hover:text-white", cursor: "cursor-pointer" },',
        '  occupied:  { bg: "bg-gray-200",      border: "border-gray-300",  text: "text-gray-400",  hover: "",                                       cursor: "cursor-not-allowed" },',
        '  reserved:  { bg: "bg-amber-100",     border: "border-amber-400", text: "text-amber-600", hover: "",                                       cursor: "cursor-not-allowed" },',
        '  selected:  { bg: "bg-[#1B2A6B]",     border: "border-[#1B2A6B]", text: "text-white",    hover: "",                                       cursor: "cursor-pointer" },',
        '  recommended:{ bg: "bg-green-100",    border: "border-green-500", text: "text-green-700", hover: "hover:bg-green-500 hover:text-white",    cursor: "cursor-pointer" },',
        '};',
        '',
        'function SeatButton({ seat, isSelected, isRecommended, onClick }) {',
        '  const status = isSelected ? "selected" : isRecommended ? "recommended" : seat.status;',
        '  const cfg = STATUS_CONFIG[status] || STATUS_CONFIG.occupied;',
        '  const isAvail = seat.status === "available";',
        '',
        '  return (',
        '    <motion.button',
        '      whileHover={isAvail ? { scale: 1.1 } : {}}',
        '      whileTap={isAvail ? { scale: 0.95 } : {}}',
        '      onClick={() => isAvail && onClick(seat)}',
        '      disabled={!isAvail}',
        '      title={seat.seat_number + " — " + seat.status}',
        '      className={"relative rounded-xl border-2 w-14 h-14 flex flex-col items-center justify-center transition-all duration-150 font-bold text-xs " + cfg.bg + " " + cfg.border + " " + cfg.text + " " + cfg.hover + " " + cfg.cursor}>',
        '      <span className="text-lg">{isSelected ? "✓" : seat.floor === 2 ? "🪑" : "💺"}</span>',
        '      <span className="text-[10px] leading-none">{seat.seat_number}</span>',
        '      {isRecommended && !isSelected && (',
        '        <span className="absolute -top-1 -right-1 w-4 h-4 bg-green-500 rounded-full flex items-center justify-center">',
        '          <Star size={8} className="text-white"/>',
        '        </span>',
        '      )}',
        '    </motion.button>',
        '  );',
        '}',
        '',
        'function FloorMap({ seats, selected, recommended, onSelect, floor }) {',
        '  const rows = {};',
        '  seats.forEach(s => { if (!rows[s.row]) rows[s.row] = []; rows[s.row].push(s); });',
        '  return (',
        '    <div className="bg-gray-50 rounded-2xl p-4">',
        '      <div className="bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] rounded-xl text-center text-white text-xs py-2 mb-4 font-bold tracking-widest">',
        '        🚌 FRENTE DEL BUS — PISO {floor}',
        '      </div>',
        '      <div className="flex flex-col gap-2">',
        '        {Object.entries(rows).sort((a,b)=>+a[0]-+b[0]).map(([row, seatsInRow]) => (',
        '          <div key={row} className="flex gap-2 justify-center items-center">',
        '            <span className="text-xs text-gray-400 w-4 text-center">{row}</span>',
        '            {seatsInRow.sort((a,b)=>a.column-b.column).map((s,i) => (',
        '              <div key={s.id}>',
        '                {i === 1 && <div className="w-6"/>}',
        '                <SeatButton seat={s} isSelected={selected?.id===s.id} isRecommended={recommended?.id===s.id} onClick={onSelect}/>',
        '              </div>',
        '            ))}',
        '          </div>',
        '        ))}',
        '      </div>',
        '    </div>',
        '  );',
        '}',
        '',
        'export default function SeatMap({ schedule, onSeatSelected }) {',
        '  const [seatData, setSeatData] = useState(null);',
        '  const [selected, setSelected] = useState(null);',
        '  const [activeFloor, setActiveFloor] = useState(1);',
        '  const [loading, setLoading] = useState(true);',
        '  const [preference, setPreference] = useState("window");',
        '  const [recommended, setRecommended] = useState(null);',
        '',
        '  useEffect(() => {',
        '    getSeatMap(schedule.id).then(r => {',
        '      setSeatData(r.data);',
        '      setLoading(false);',
        '    }).catch(() => setLoading(false));',
        '  }, [schedule.id]);',
        '',
        '  useEffect(() => {',
        '    if (!seatData) return;',
        '    const all = [...(seatData.floor_1||[]), ...(seatData.floor_2||[])].filter(s => s.status === "available");',
        '    if (all.length === 0) return;',
        '    let best;',
        '    if (preference === "window") best = all.find(s => s.column === 1) || all[0];',
        '    else if (preference === "aisle") best = all.find(s => s.column === 2) || all[0];',
        '    else best = all.find(s => s.row <= 3) || all[0];',
        '    setRecommended(best);',
        '  }, [seatData, preference]);',
        '',
        '  const handleSelect = (seat) => {',
        '    setSelected(seat);',
        '    onSeatSelected(seat);',
        '  };',
        '',
        '  if (loading) return (',
        '    <div className="card max-w-2xl mx-auto animate-pulse">',
        '      <div className="h-8 bg-gray-200 rounded mb-4 w-48"/>',
        '      <div className="h-64 bg-gray-200 rounded-xl"/>',
        '    </div>',
        '  );',
        '',
        '  const floors = [',
        '    { num: 1, seats: seatData?.floor_1 || [] },',
        '    { num: 2, seats: seatData?.floor_2 || [] },',
        '  ].filter(f => f.seats.length > 0);',
        '',
        '  const available = (seatData?.floor_1?.length||0) + (seatData?.floor_2?.length||0);',
        '  const occupied = floors.flatMap(f=>f.seats).filter(s=>s.status!=="available").length;',
        '',
        '  return (',
        '    <div className="max-w-2xl mx-auto">',
        '      {selected && <SeatTimer onExpire={() => { setSelected(null); onSeatSelected(null); }}/>}',
        '      <div className="card">',
        '        <div className="flex items-center justify-between mb-4">',
        '          <h3 className="text-lg font-bold text-[#1B2A6B]">Selecciona tu asiento</h3>',
        '          <div className="flex gap-3 text-xs">',
        '            <span className="flex items-center gap-1"><span className="w-3 h-3 rounded bg-white border-2 border-[#1B2A6B] inline-block"></span> Libre</span>',
        '            <span className="flex items-center gap-1"><span className="w-3 h-3 rounded bg-green-100 border-2 border-green-500 inline-block"></span> Recomendado</span>',
        '            <span className="flex items-center gap-1"><span className="w-3 h-3 rounded bg-[#1B2A6B] inline-block"></span> Seleccionado</span>',
        '            <span className="flex items-center gap-1"><span className="w-3 h-3 rounded bg-gray-200 inline-block"></span> Ocupado</span>',
        '          </div>',
        '        </div>',
        '        <div className="mb-4 p-3 bg-gray-50 rounded-xl">',
        '          <p className="text-xs font-bold text-gray-500 uppercase mb-2">Preferencia de asiento</p>',
        '          <div className="flex gap-2">',
        '            {[{id:"window",label:"🪟 Ventana"},{id:"aisle",label:"🚶 Pasillo"},{id:"front",label:"⬆️ Adelante"}].map(p => (',
        '              <button key={p.id} onClick={() => setPreference(p.id)}',
        '                className={"px-3 py-1 rounded-full text-xs transition-all font-semibold " + (preference===p.id ? "bg-[#1B2A6B] text-white" : "bg-white border border-gray-300 text-gray-600")}>',
        '                {p.label}',
        '              </button>',
        '            ))}',
        '          </div>',
        '        </div>',
        '        {floors.length > 1 && (',
        '          <div className="flex gap-2 mb-4">',
        '            {floors.map(f => (',
        '              <button key={f.num} onClick={() => setActiveFloor(f.num)}',
        '                className={"px-4 py-2 rounded-lg font-semibold text-sm transition-all " + (activeFloor===f.num ? "bg-[#1B2A6B] text-white" : "bg-gray-100 text-gray-600")}>',
        '                Piso {f.num}',
        '              </button>',
        '            ))}',
        '          </div>',
        '        )}',
        '        {floors.filter(f=>f.num===activeFloor).map(f => (',
        '          <FloorMap key={f.num} seats={f.seats} selected={selected} recommended={recommended} onSelect={handleSelect} floor={f.num}/>',
        '        ))}',
        '        <AnimatePresence>',
        '          {selected && (',
        '            <motion.div initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:10}}',
        '              className="mt-4 p-4 bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] rounded-xl text-white text-center font-bold">',
        '              ✅ Asiento {selected.seat_number} seleccionado — Piso {selected.floor}',
        '            </motion.div>',
        '          )}',
        '        </AnimatePresence>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: SeatMap.jsx premium')