with open('src/components/SeatMap.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { getSeatMap, reserveSeat } from ' + chr(39) + '../api' + chr(39) + ';\n'
'\n'
'const STATUS_STYLES = {\n'
'  available: ' + chr(39) + 'bg-white border-2 border-[#1B2A6B] text-[#1B2A6B] hover:bg-[#1B2A6B] hover:text-white cursor-pointer' + chr(39) + ',\n'
'  occupied:  ' + chr(39) + 'bg-gray-300 border-2 border-gray-400 text-gray-500 cursor-not-allowed' + chr(39) + ',\n'
'  reserved:  ' + chr(39) + 'bg-amber-200 border-2 border-amber-400 text-amber-700 cursor-not-allowed' + chr(39) + ',\n'
'  selected:  ' + chr(39) + 'bg-[#1B2A6B] border-2 border-[#1B2A6B] text-white cursor-pointer' + chr(39) + ',\n'
'};\n'
'\n'
'function SeatButton({ seat, selected, onClick }) {\n'
'  const isAvailable = seat.status === ' + chr(39) + 'available' + chr(39) + ';\n'
'  const isSelected = selected?.id === seat.id;\n'
'  const style = isSelected ? STATUS_STYLES.selected : STATUS_STYLES[seat.status] || STATUS_STYLES.occupied;\n'
'  return (\n'
'    <button\n'
'      className={' + chr(34) + 'rounded-lg p-2 text-xs font-bold transition-all duration-150 w-12 h-12 flex flex-col items-center justify-center ' + chr(34) + ' + style}\n'
'      onClick={() => isAvailable && onClick(seat)}\n'
'      disabled={!isAvailable}\n'
'      title={seat.seat_number + ' + chr(34) + ' - ' + chr(34) + ' + seat.status}\n'
'    >\n'
'      <span className=' + chr(34) + 'text-lg' + chr(34) + '>💺</span>\n'
'      <span>{seat.seat_number}</span>\n'
'    </button>\n'
'  );\n'
'}\n'
'\n'
'function FloorMap({ seats, selected, onSelect, floor }) {\n'
'  const rows = {};\n'
'  seats.forEach(s => {\n'
'    if (!rows[s.row]) rows[s.row] = [];\n'
'    rows[s.row].push(s);\n'
'  });\n'
'  return (\n'
'    <div>\n'
'      <div className=' + chr(34) + 'flex items-center justify-between mb-3' + chr(34) + '>\n'
'        <span className=' + chr(34) + 'font-semibold text-[#1B2A6B]' + chr(34) + '>Piso {floor}</span>\n'
'        <div className=' + chr(34) + 'flex gap-4 text-xs' + chr(34) + '>\n'
'          <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><span className=' + chr(34) + 'w-4 h-4 rounded bg-white border-2 border-[#1B2A6B] inline-block' + chr(34) + '></span> Libre</span>\n'
'          <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><span className=' + chr(34) + 'w-4 h-4 rounded bg-[#1B2A6B] inline-block' + chr(34) + '></span> Seleccionado</span>\n'
'          <span className=' + chr(34) + 'flex items-center gap-1' + chr(34) + '><span className=' + chr(34) + 'w-4 h-4 rounded bg-gray-300 inline-block' + chr(34) + '></span> Ocupado</span>\n'
'        </div>\n'
'      </div>\n'
'      <div className=' + chr(34) + 'bg-gray-100 rounded-xl p-4' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'bg-gray-300 rounded-lg text-center text-xs text-gray-600 py-2 mb-4 font-semibold' + chr(34) + '>🚌 FRENTE DEL BUS</div>\n'
'        <div className=' + chr(34) + 'flex flex-col gap-2' + chr(34) + '>\n'
'          {Object.entries(rows).map(([row, seatsInRow]) => (\n'
'            <div key={row} className=' + chr(34) + 'flex gap-2 justify-center' + chr(34) + '>\n'
'              {seatsInRow.sort((a,b)=>a.column-b.column).map(s => (\n'
'                <SeatButton key={s.id} seat={s} selected={selected} onClick={onSelect}/>\n'
'              ))}\n'
'            </div>\n'
'          ))}\n'
'        </div>\n'
'      </div>\n'
'    </div>\n'
'  );\n'
'}\n'
'\n'
'export default function SeatMap({ schedule, onSeatSelected }) {\n'
'  const [seatData, setSeatData] = useState(null);\n'
'  const [selected, setSelected] = useState(null);\n'
'  const [activeFloor, setActiveFloor] = useState(1);\n'
'  const [loading, setLoading] = useState(true);\n'
'\n'
'  useEffect(() => {\n'
'    getSeatMap(schedule.id).then(r => { setSeatData(r.data); setLoading(false); }).catch(() => setLoading(false));\n'
'  }, [schedule.id]);\n'
'\n'
'  const handleSelect = async (seat) => {\n'
'    setSelected(seat);\n'
'    onSeatSelected(seat);\n'
'  };\n'
'\n'
'  if (loading) return <div className=' + chr(34) + 'text-center py-12 text-gray-500' + chr(34) + '>Cargando mapa de asientos...</div>;\n'
'\n'
'  const floors = [\n'
'    { num: 1, seats: seatData?.floor_1 || [] },\n'
'    { num: 2, seats: seatData?.floor_2 || [] },\n'
'  ].filter(f => f.seats.length > 0);\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'card max-w-2xl mx-auto' + chr(34) + '>\n'
'      <h3 className=' + chr(34) + 'text-lg font-bold text-[#1B2A6B] mb-4' + chr(34) + '>Selecciona tu asiento</h3>\n'
'      {floors.length > 1 && (\n'
'        <div className=' + chr(34) + 'flex gap-2 mb-4' + chr(34) + '>\n'
'          {floors.map(f => (\n'
'            <button key={f.num} onClick={()=>setActiveFloor(f.num)}\n'
'              className={' + chr(34) + 'px-4 py-2 rounded-lg font-semibold text-sm transition-all ' + chr(34) + ' + (activeFloor===f.num?' + chr(39) + 'bg-[#1B2A6B] text-white' + chr(39) + ':' + chr(39) + 'bg-gray-100 text-gray-600' + chr(39) + ')}>\n'
'              Piso {f.num}\n'
'            </button>\n'
'          ))}\n'
'        </div>\n'
'      )}\n'
'      {floors.filter(f=>f.num===activeFloor).map(f => (\n'
'        <FloorMap key={f.num} seats={f.seats} selected={selected} onSelect={handleSelect} floor={f.num}/>\n'
'      ))}\n'
'      {selected && (\n'
'        <div className=' + chr(34) + 'mt-4 p-3 bg-[#f0f4ff] rounded-lg text-[#1B2A6B] font-semibold text-center' + chr(34) + '>\n'
'          ✅ Asiento seleccionado: {selected.seat_number} — Piso {selected.floor}\n'
'        </div>\n'
'      )}\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: SeatMap.jsx')