with open('src/App.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { motion, AnimatePresence } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import SearchHero from ' + chr(39) + './components/SearchHero' + chr(39) + ';',
        'import SearchResults from ' + chr(39) + './components/SearchResults' + chr(39) + ';',
        'import SeatMap from ' + chr(39) + './components/SeatMap' + chr(39) + ';',
        'import Checkout from ' + chr(39) + './components/Checkout' + chr(39) + ';',
        'import MyTrips from ' + chr(39) + './components/MyTrips' + chr(39) + ';',
        'import BottomNav from ' + chr(39) + './components/BottomNav' + chr(39) + ';',
        'import { useStore } from ' + chr(39) + './store' + chr(39) + ';',
        '',
        'export default function App() {',
        '  const [page, setPage] = useState("search");',
        '  const [step, setStep] = useState("search");',
        '  const [results, setResults] = useState(null);',
        '  const [searchInfo, setSearchInfo] = useState(null);',
        '  const [selectedSchedule, setSelectedSchedule] = useState(null);',
        '  const [selectedSeat, setSelectedSeat] = useState(null);',
        '  const [loading, setLoading] = useState(false);',
        '  const { addBooking } = useStore();',
        '',
        '  const handleResults = (data, info) => {',
        '    setResults(data); setSearchInfo(info); setStep("results");',
        '  };',
        '',
        '  const handleSelectSchedule = (s) => {',
        '    setSelectedSchedule(s); setStep("seats");',
        '  };',
        '',
        '  const handleSelectSeat = (seat) => setSelectedSeat(seat);',
        '',
        '  const handleCheckout = () => { if (selectedSeat) setStep("checkout"); };',
        '',
        '  const handleBack = () => {',
        '    if (step === "checkout") setStep("seats");',
        '    else if (step === "seats") setStep("results");',
        '    else setStep("search");',
        '  };',
        '',
        '  const handleBookingComplete = (booking) => {',
        '    addBooking({',
        '      ...booking,',
        '      origin: selectedSchedule?.origin,',
        '      destination: selectedSchedule?.destination,',
        '      company: selectedSchedule?.company,',
        '      seat_number: selectedSeat?.seat_number,',
        '    });',
        '  };',
        '',
        '  const goSearch = () => { setPage("search"); setStep("search"); };',
        '',
        '  return (',
        '    <div className="min-h-screen bg-gray-50 pb-16 md:pb-0">',
        '      <AnimatePresence mode="wait">',
        '        {page === "search" && (',
        '          <motion.div key="search-page" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>',
        '            {step === "search" && <SearchHero onResults={handleResults}/>}',
        '            {step === "results" && (',
        '              <SearchResults results={results} searchInfo={searchInfo} onSelect={handleSelectSchedule} loading={loading}/>',
        '            )}',
        '            {step === "seats" && (',
        '              <div className="max-w-4xl mx-auto px-4 py-8">',
        '                <button onClick={handleBack} className="text-[#1B2A6B] mb-4 flex items-center gap-1 hover:underline text-sm">← Volver</button>',
        '                <div className="card mb-4 flex items-center justify-between">',
        '                  <div>',
        '                    <p className="font-bold text-[#1B2A6B]">{selectedSchedule?.origin} → {selectedSchedule?.destination}</p>',
        '                    <p className="text-sm text-gray-500">{selectedSchedule?.company} · {selectedSchedule?.bus_type}</p>',
        '                  </div>',
        '                  <div className="text-right">',
        '                    <p className="text-2xl font-black text-[#1B2A6B]">Bs. {selectedSchedule?.price_normal}</p>',
        '                    <p className="text-xs text-gray-400">+ Bs. {selectedSchedule?.terminal_fee} terminal</p>',
        '                  </div>',
        '                </div>',
        '                <SeatMap schedule={selectedSchedule} onSeatSelected={handleSelectSeat}/>',
        '                <AnimatePresence>',
        '                  {selectedSeat && (',
        '                    <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="text-center mt-6">',
        '                      <motion.button onClick={handleCheckout}',
        '                        whileHover={{scale:1.05}} whileTap={{scale:0.95}}',
        '                        className="bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] text-white font-bold px-12 py-4 rounded-2xl text-lg shadow-lg">',
        '                        Continuar al Pago →',
        '                      </motion.button>',
        '                    </motion.div>',
        '                  )}',
        '                </AnimatePresence>',
        '              </div>',
        '            )}',
        '            {step === "checkout" && (',
        '              <Checkout schedule={selectedSchedule} seat={selectedSeat} onBack={handleBack} onComplete={handleBookingComplete}/>',
        '            )}',
        '          </motion.div>',
        '        )}',
        '        {page === "trips" && (',
        '          <motion.div key="trips-page" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}>',
        '            <div className="bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] px-6 py-8 text-white">',
        '              <h1 className="text-2xl font-black">Bolivia <span className="text-[#D4AF37]">Bus</span></h1>',
        '              <p className="text-blue-200 text-sm">Historial de viajes</p>',
        '            </div>',
        '            <MyTrips onSearch={goSearch}/>',
        '          </motion.div>',
        '        )}',
        '        {page === "tracking" && (',
        '          <motion.div key="tracking-page" initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-20}}>',
        '            <div className="bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] px-6 py-8 text-white">',
        '              <h1 className="text-2xl font-black">Bolivia <span className="text-[#D4AF37]">Bus</span></h1>',
        '              <p className="text-blue-200 text-sm">Rastreo de tu bus en tiempo real</p>',
        '            </div>',
        '            <div className="p-4 text-center text-gray-400 py-16">',
        '              <p className="text-lg font-semibold mb-2">Rastreo disponible con tu ticket</p>',
        '              <p className="text-sm">Compra tu pasaje para ver la ubicacion de tu bus en tiempo real</p>',
        '              <button onClick={goSearch} className="btn-primary mt-4">Comprar pasaje</button>',
        '            </div>',
        '          </motion.div>',
        '        )}',
        '      </AnimatePresence>',
        '      <footer className="bg-[#1B2A6B] text-white text-center py-6 mt-12 text-sm hidden md:block">',
        '        <p>Bolivia Bus © 2026 | Sistema Integral de Ticketing Terrestre</p>',
        '        <p className="text-[#D4AF37] mt-1">La Paz · Cochabamba · Santa Cruz · Oruro · Potosi · Sucre · Tarija</p>',
        '      </footer>',
        '      <BottomNav active={page} onNav={setPage}/>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: App.jsx premium')