with open('src/components/BottomNav.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { motion } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { Search, Ticket, Bus } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        'import { useStore } from ' + chr(39) + '../store' + chr(39) + ';',
        '',
        'const NAV_ITEMS = [',
        '  { id: "search", label: "Buscar", icon: Search },',
        '  { id: "trips", label: "Mis Viajes", icon: Ticket },',
        '  { id: "tracking", label: "Rastreo", icon: Bus },',
        '];',
        '',
        'export default function BottomNav({ active, onNav }) {',
        '  const { bookings } = useStore();',
        '  return (',
        '    <div className="fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 shadow-2xl z-50 md:hidden">',
        '      <div className="flex items-center justify-around px-2 py-2">',
        '        {NAV_ITEMS.map(item => (',
        '          <button key={item.id} onClick={() => onNav(item.id)}',
        '            className="flex flex-col items-center gap-1 px-4 py-2 rounded-xl transition-all relative"',
        '            style={{ color: active === item.id ? "#1B2A6B" : "#9CA3AF" }}>',
        '            {active === item.id && (',
        '              <motion.div layoutId="nav-indicator"',
        '                className="absolute inset-0 bg-[#1B2A6B]/10 rounded-xl"',
        '                transition={{ type: "spring", bounce: 0.3 }}/>',
        '            )}',
        '            <div className="relative">',
        '              <item.icon size={22}/>',
        '              {item.id === "trips" && bookings.length > 0 && (',
        '                <span className="absolute -top-1 -right-1 w-4 h-4 bg-[#C8102E] rounded-full text-white text-[9px] flex items-center justify-center font-bold">',
        '                  {bookings.length}',
        '                </span>',
        '              )}',
        '            </div>',
        '            <span className="text-[10px] font-semibold">{item.label}</span>',
        '          </button>',
        '        ))}',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: BottomNav.jsx')