with open('src/components/SearchResults.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { useState } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { motion, AnimatePresence } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { Clock, Bus, MapPin, ChevronRight, SlidersHorizontal } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        'import SkeletonCard from ' + chr(39) + './SkeletonCard' + chr(39) + ';',
        '',
        'const BUS_COLORS = {',
        '  normal:   { bg: "bg-blue-100",   text: "text-blue-700",   label: "Normal",       icon: "🚌" },',
        '  semicama: { bg: "bg-purple-100",  text: "text-purple-700", label: "Semicama",     icon: "🚎" },',
        '  cama:     { bg: "bg-amber-100",   text: "text-amber-700",  label: "Cama / Lecho", icon: "🛌" },',
        '};',
        '',
        'function formatTime(dt) {',
        '  return new Date(dt).toLocaleTimeString("es-BO", { hour: "2-digit", minute: "2-digit" });',
        '}',
        '',
        'function getPrice(s) {',
        '  if (s.bus_type === "cama") return s.price_cama;',
        '  if (s.bus_type === "semicama") return s.price_semicama;',
        '  return s.price_normal;',
        '}',
        '',
        'export default function SearchResults({ results, searchInfo, onSelect, loading }) {',
        '  const [sortBy, setSortBy] = useState("price");',
        '  const [filterType, setFilterType] = useState("all");',
        '  const [showFilters, setShowFilters] = useState(false);',
        '',
        '  if (loading) return (',
        '    <div className="max-w-4xl mx-auto px-4 py-8 flex flex-col gap-4">',
        '      {[1,2,3].map(i => <SkeletonCard key={i}/>)}',
        '    </div>',
        '  );',
        '  if (!results) return null;',
        '',
        '  let filtered = [...results];',
        '  if (filterType !== "all") filtered = filtered.filter(s => s.bus_type === filterType);',
        '  if (sortBy === "price") filtered.sort((a,b) => getPrice(a) - getPrice(b));',
        '  if (sortBy === "time") filtered.sort((a,b) => new Date(a.departure_time) - new Date(b.departure_time));',
        '  if (sortBy === "seats") filtered.sort((a,b) => b.available_seats - a.available_seats);',
        '',
        '  return (',
        '    <div className="max-w-4xl mx-auto px-4 py-8">',
        '      <motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="mb-6">',
        '        <div className="flex items-center gap-3 mb-4 flex-wrap">',
        '          <div className="flex items-center gap-2 bg-[#1B2A6B] text-white px-4 py-2 rounded-full text-sm font-semibold">',
        '            <MapPin size={14}/>{searchInfo?.origin}<span className="text-[#D4AF37]">→</span>{searchInfo?.destination}',
        '          </div>',
        '          <span className="text-sm text-gray-500 ml-auto">{filtered.length} viaje{filtered.length!==1?"s":""}</span>',
        '          <button onClick={() => setShowFilters(!showFilters)}',
        '            className={"flex items-center gap-1 text-sm px-3 py-2 rounded-lg border transition-all " + (showFilters ? "bg-[#1B2A6B] text-white border-[#1B2A6B]" : "border-gray-300 text-gray-600")}>',
        '            <SlidersHorizontal size={14}/> Filtros',
        '          </button>',
        '        </div>',
        '        <AnimatePresence>',
        '          {showFilters && (',
        '            <motion.div initial={{opacity:0,height:0}} animate={{opacity:1,height:"auto"}} exit={{opacity:0,height:0}}',
        '              className="bg-white rounded-xl border border-gray-200 p-4 mb-4 overflow-hidden">',
        '              <div className="flex flex-wrap gap-4">',
        '                <div>',
        '                  <p className="text-xs font-bold text-gray-500 uppercase mb-2">Tipo de Bus</p>',
        '                  <div className="flex gap-2 flex-wrap">',
        '                    {[{id:"all",label:"Todos"},{id:"normal",label:"🚌 Normal"},{id:"semicama",label:"🚎 Semicama"},{id:"cama",label:"🛌 Cama"}].map(f => (',
        '                      <button key={f.id} onClick={() => setFilterType(f.id)}',
        '                        className={"px-3 py-1 rounded-full text-sm transition-all " + (filterType === f.id ? "bg-[#1B2A6B] text-white" : "bg-gray-100 text-gray-600")}>',
        '                        {f.label}',
        '                      </button>',
        '                    ))}',
        '                  </div>',
        '                </div>',
        '                <div>',
        '                  <p className="text-xs font-bold text-gray-500 uppercase mb-2">Ordenar por</p>',
        '                  <div className="flex gap-2">',
        '                    {[{id:"price",label:"💰 Precio"},{id:"time",label:"⏰ Hora"},{id:"seats",label:"💺 Asientos"}].map(s => (',
        '                      <button key={s.id} onClick={() => setSortBy(s.id)}',
        '                        className={"px-3 py-1 rounded-full text-sm transition-all " + (sortBy === s.id ? "bg-[#1B2A6B] text-white" : "bg-gray-100 text-gray-600")}>',
        '                        {s.label}',
        '                      </button>',
        '                    ))}',
        '                  </div>',
        '                </div>',
        '              </div>',
        '            </motion.div>',
        '          )}',
        '        </AnimatePresence>',
        '      </motion.div>',
        '      {filtered.length === 0 && (',
        '        <div className="text-center py-16">',
        '          <Bus size={48} className="mx-auto text-gray-300 mb-4"/>',
        '          <p className="text-gray-500 text-lg">No hay viajes disponibles.</p>',
        '        </div>',
        '      )}',
        '      <div className="flex flex-col gap-4">',
        '        {filtered.map((s, i) => {',
        '          const bs = BUS_COLORS[s.bus_type] || BUS_COLORS.normal;',
        '          const price = getPrice(s);',
        '          return (',
        '            <motion.div key={s.id}',
        '              initial={{opacity:0, y:20}} animate={{opacity:1, y:0}} transition={{delay: i*0.08}}',
        '              whileHover={{scale:1.01, boxShadow:"0 8px 30px rgba(27,42,107,0.12)"}}',
        '              className="bg-white rounded-2xl shadow-md p-5 border border-gray-100 cursor-pointer border-l-4 border-l-[#1B2A6B]"',
        '              onClick={() => onSelect(s)}>',
        '              <div className="flex flex-col md:flex-row md:items-center gap-4">',
        '                <div className="flex-1">',
        '                  <div className="flex items-center gap-3 mb-2 flex-wrap">',
        '                    <span className="text-2xl font-black text-[#1B2A6B]">{formatTime(s.departure_time)}</span>',
        '                    <div className="flex-1 flex items-center gap-1 min-w-[60px]">',
        '                      <div className="h-0.5 flex-1 bg-gray-300 rounded"/>',
        '                      <span className="text-xs text-gray-400 px-1">{s.duration_hours}h</span>',
        '                      <div className="h-0.5 flex-1 bg-gray-300 rounded"/>',
        '                    </div>',
        '                    <span className="text-2xl font-black text-gray-500">{formatTime(s.arrival_time)}</span>',
        '                    <span className={"text-xs px-3 py-1 rounded-full font-bold " + bs.bg + " " + bs.text}>',
        '                      {bs.icon} {bs.label}',
        '                    </span>',
        '                  </div>',
        '                  <div className="flex items-center gap-4 text-sm text-gray-500 flex-wrap">',
        '                    <span className="flex items-center gap-1"><Bus size={14}/> {s.company}</span>',
        '                    <span className="flex items-center gap-1 text-green-600 font-semibold">💺 {s.available_seats} libres</span>',
        '                    <span className="flex items-center gap-1"><Clock size={14}/> {s.duration_hours}h</span>',
        '                  </div>',
        '                </div>',
        '                <div className="text-right">',
        '                  <div className="text-3xl font-black text-[#1B2A6B]">Bs. {price}</div>',
        '                  <div className="text-xs text-gray-400">+ Bs. {s.terminal_fee} terminal</div>',
        '                  <div className="text-sm font-bold text-[#1B2A6B] mt-1">Total: Bs. {price + s.terminal_fee}</div>',
        '                  <motion.button whileHover={{scale:1.05}} whileTap={{scale:0.95}}',
        '                    className="mt-2 bg-[#1B2A6B] text-white text-sm font-semibold px-5 py-2 rounded-xl flex items-center gap-1 ml-auto hover:bg-[#D4AF37] hover:text-[#1B2A6B] transition-all">',
        '                    Seleccionar <ChevronRight size={16}/>',
        '                  </motion.button>',
        '                </div>',
        '              </div>',
        '            </motion.div>',
        '          );',
        '        })}',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: SearchResults.jsx')