with open('src/components/Checkout.jsx', 'w', encoding='utf-8') as f:
    f.write('\n'.join([
        'import { useState } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { createBooking, downloadPDF } from ' + chr(39) + '../api' + chr(39) + ';',
        'import { User, Download, CheckCircle, QrCode, CreditCard, ArrowLeft } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        '',
        'const QR_METHODS = [',
        '  { id: ' + chr(39) + 'qr_bcp' + chr(39) + ', label: ' + chr(39) + 'QR BCP' + chr(39) + ', color: ' + chr(39) + 'bg-green-600' + chr(39) + ', desc: ' + chr(39) + 'Paga con tu app del banco' + chr(39) + ' },',
        '  { id: ' + chr(39) + 'libelula' + chr(39) + ', label: ' + chr(39) + 'Libélula' + chr(39) + ', color: ' + chr(39) + 'bg-blue-600' + chr(39) + ', desc: ' + chr(39) + 'Paga con tarjeta débito/crédito' + chr(39) + ' },',
        '  { id: ' + chr(39) + 'efectivo' + chr(39) + ', label: ' + chr(39) + 'Efectivo' + chr(39) + ', color: ' + chr(39) + 'bg-amber-600' + chr(39) + ', desc: ' + chr(39) + 'Paga en ventanilla de la terminal' + chr(39) + ' },',
        '];',
        '',
        'function QRDisplay({ amount, method }) {',
        '  const qrData = JSON.stringify({ method, amount, ref: Date.now() });',
        '  const qrUrl = ' + chr(34) + 'https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=' + chr(34) + ' + encodeURIComponent(qrData);',
        '  return (',
        '    <div className=' + chr(34) + 'flex flex-col items-center gap-4 p-6 bg-white rounded-xl border-2 border-[#1B2A6B]' + chr(34) + '>',
        '      <p className=' + chr(34) + 'font-bold text-[#1B2A6B] text-lg' + chr(34) + '>Escanea para pagar</p>',
        '      <img src={qrUrl} alt=' + chr(34) + 'QR Pago' + chr(34) + ' className=' + chr(34) + 'w-48 h-48 rounded-lg shadow-md' + chr(34) + '/>',
        '      <div className=' + chr(34) + 'text-center' + chr(34) + '>',
        '        <p className=' + chr(34) + 'text-3xl font-bold text-[#1B2A6B]' + chr(34) + '>Bs. {amount.toFixed(2)}</p>',
        '        <p className=' + chr(34) + 'text-sm text-gray-500 mt-1' + chr(34) + '>Monto total a pagar</p>',
        '      </div>',
        '      <div className=' + chr(34) + 'w-full bg-gray-50 rounded-lg p-3 text-xs text-gray-500 text-center' + chr(34) + '>',
        '        <p>Ref: BOL-{Date.now().toString().slice(-8)}</p>',
        '        <p className=' + chr(34) + 'text-amber-600 font-semibold mt-1' + chr(34) + '>⏱ QR válido por 15 minutos</p>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
        '',
        'export default function Checkout({ schedule, seat, onBack }) {',
        '  const [form, setForm] = useState({ passenger_name: ' + chr(39) + chr(39) + ', passenger_ci: ' + chr(39) + chr(39) + ' });',
        '  const [booking, setBooking] = useState(null);',
        '  const [loading, setLoading] = useState(false);',
        '  const [error, setError] = useState(' + chr(39) + chr(39) + ');',
        '  const [step, setStep] = useState(1);',
        '  const [payMethod, setPayMethod] = useState(null);',
        '  const [paying, setPaying] = useState(false);',
        '',
        '  const price = schedule.bus_type === ' + chr(39) + 'cama' + chr(39) + ' ? schedule.price_cama : schedule.bus_type === ' + chr(39) + 'semicama' + chr(39) + ' ? schedule.price_semicama : schedule.price_normal;',
        '  const total = price + schedule.terminal_fee;',
        '',
        '  const handleBook = async () => {',
        '    if (!form.passenger_name || !form.passenger_ci) { setError(' + chr(39) + 'Completa todos los campos' + chr(39) + '); return; }',
        '    setLoading(true); setError(' + chr(39) + chr(39) + ');',
        '    try {',
        '      const res = await createBooking({ schedule_id: schedule.id, seat_id: seat.id, ...form });',
        '      setBooking(res.data);',
        '      setStep(2);',
        '    } catch (e) { setError(e.response?.data?.detail || ' + chr(39) + 'Error al reservar' + chr(39) + '); }',
        '    finally { setLoading(false); }',
        '  };',
        '',
        '  const handlePay = async () => {',
        '    if (!payMethod) return;',
        '    setPaying(true);',
        '    await new Promise(r => setTimeout(r, 2000));',
        '    setPaying(false);',
        '    setStep(3);',
        '  };',
        '',
        '  const handleDownload = async () => {',
        '    try {',
        '      const res = await downloadPDF(booking.id);',
        '      const url = URL.createObjectURL(new Blob([res.data], { type: ' + chr(39) + 'application/pdf' + chr(39) + ' }));',
        '      const a = document.createElement(' + chr(39) + 'a' + chr(39) + ');',
        '      a.href = url; a.download = ' + chr(34) + 'ticket_boliviabus.pdf' + chr(34) + '; a.click();',
        '    } catch { alert(' + chr(39) + 'Error al descargar PDF' + chr(39) + '); }',
        '  };',
        '',
        '  const STEPS = [',
        '    { n: 1, label: ' + chr(39) + 'Datos' + chr(39) + ' },',
        '    { n: 2, label: ' + chr(39) + 'Pago' + chr(39) + ' },',
        '    { n: 3, label: ' + chr(39) + 'Confirmado' + chr(39) + ' },',
        '  ];',
        '',
        '  return (',
        '    <div className=' + chr(34) + 'max-w-lg mx-auto px-4 py-8' + chr(34) + '>',
        '      <button onClick={onBack} className=' + chr(34) + 'text-[#1B2A6B] mb-4 flex items-center gap-1 hover:underline' + chr(34) + '>',
        '        <ArrowLeft size={16}/> Volver',
        '      </button>',
        '      <div className=' + chr(34) + 'flex items-center justify-center gap-2 mb-6' + chr(34) + '>',
        '        {STEPS.map((s, i) => (',
        '          <div key={s.n} className=' + chr(34) + 'flex items-center gap-2' + chr(34) + '>',
        '            <div className={' + chr(34) + 'w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ' + chr(34) + ' + (step >= s.n ? ' + chr(39) + 'bg-[#1B2A6B] text-white' + chr(39) + ' : ' + chr(39) + 'bg-gray-200 text-gray-500' + chr(39) + ')}>{s.n}</div>',
        '            <span className={' + chr(34) + 'text-sm ' + chr(34) + ' + (step >= s.n ? ' + chr(39) + 'text-[#1B2A6B] font-semibold' + chr(39) + ' : ' + chr(39) + 'text-gray-400' + chr(39) + ')}>{s.label}</span>',
        '            {i < STEPS.length - 1 && <div className=' + chr(34) + 'w-8 h-0.5 bg-gray-200' + chr(34) + '></div>}',
        '          </div>',
        '        ))}',
        '      </div>',
        '',
        '      {step === 1 && (',
        '        <div className=' + chr(34) + 'card' + chr(34) + '>',
        '          <h3 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B] mb-4 flex items-center gap-2' + chr(34) + '><User size={20}/> Datos del Pasajero</h3>',
        '          <div className=' + chr(34) + 'bg-[#f0f4ff] rounded-xl p-4 mb-4 grid grid-cols-2 gap-2 text-sm' + chr(34) + '>',
        '            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Ruta:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>{schedule.origin} → {schedule.destination}</p></div>',
        '            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Asiento:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>{seat.seat_number} Piso {seat.floor}</p></div>',
        '            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Precio base:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>Bs. {price}</p></div>',
        '            <div><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>Terminal:</span><p className=' + chr(34) + 'font-semibold' + chr(34) + '>Bs. {schedule.terminal_fee}</p></div>',
        '            <div className=' + chr(34) + 'col-span-2 border-t pt-2' + chr(34) + '><span className=' + chr(34) + 'text-gray-500' + chr(34) + '>TOTAL:</span><p className=' + chr(34) + 'font-bold text-[#1B2A6B] text-lg' + chr(34) + '>Bs. {total.toFixed(2)}</p></div>',
        '          </div>',
        '          <div className=' + chr(34) + 'flex flex-col gap-4' + chr(34) + '>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1 block' + chr(34) + '>Nombre completo</label>',
        '              <input className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-[#1B2A6B]' + chr(34) + ' placeholder=' + chr(34) + 'Ej: Juan Carlos Quispe' + chr(34) + ' value={form.passenger_name} onChange={e=>setForm({...form,passenger_name:e.target.value})}/>',
        '            </div>',
        '            <div>',
        '              <label className=' + chr(34) + 'text-sm font-semibold text-gray-700 mb-1 block' + chr(34) + '>CI (con extensión)</label>',
        '              <input className=' + chr(34) + 'w-full border border-gray-300 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-[#1B2A6B]' + chr(34) + ' placeholder=' + chr(34) + 'Ej: 1234567 LP' + chr(34) + ' value={form.passenger_ci} onChange={e=>setForm({...form,passenger_ci:e.target.value})}/>',
        '            </div>',
        '          </div>',
        '          {error && <p className=' + chr(34) + 'text-red-500 text-sm mt-3' + chr(34) + '>{error}</p>}',
        '          <button onClick={handleBook} disabled={loading} className=' + chr(34) + 'w-full mt-6 bg-[#1B2A6B] hover:bg-[#162259] text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2 transition-all' + chr(34) + '>',
        '            <CreditCard size={18}/> {loading ? ' + chr(39) + 'Procesando...' + chr(39) + ' : ' + chr(39) + 'Continuar al Pago →' + chr(39) + '}',
        '          </button>',
        '        </div>',
        '      )}',
        '',
        '      {step === 2 && booking && (',
        '        <div className=' + chr(34) + 'card' + chr(34) + '>',
        '          <h3 className=' + chr(34) + 'text-xl font-bold text-[#1B2A6B] mb-4 flex items-center gap-2' + chr(34) + '><QrCode size={20}/> Método de Pago</h3>',
        '          <div className=' + chr(34) + 'flex flex-col gap-3 mb-6' + chr(34) + '>',
        '            {QR_METHODS.map(m => (',
        '              <button key={m.id} onClick={() => setPayMethod(m.id)}',
        '                className={' + chr(34) + 'flex items-center gap-3 p-4 rounded-xl border-2 transition-all text-left ' + chr(34) + ' + (payMethod === m.id ? ' + chr(39) + 'border-[#1B2A6B] bg-[#f0f4ff]' + chr(39) + ' : ' + chr(39) + 'border-gray-200 hover:border-gray-300' + chr(39) + ')}>',
        '                <div className={' + chr(34) + 'w-10 h-10 rounded-lg flex items-center justify-center text-white font-bold text-sm ' + chr(34) + ' + m.color}>{m.label[0]}</div>',
        '                <div>',
        '                  <p className=' + chr(34) + 'font-semibold text-gray-800' + chr(34) + '>{m.label}</p>',
        '                  <p className=' + chr(34) + 'text-xs text-gray-500' + chr(34) + '>{m.desc}</p>',
        '                </div>',
        '                {payMethod === m.id && <span className=' + chr(34) + 'ml-auto text-[#1B2A6B] font-bold' + chr(34) + '>✓</span>}',
        '              </button>',
        '            ))}',
        '          </div>',
        '          {payMethod && payMethod !== ' + chr(39) + 'efectivo' + chr(39) + ' && <QRDisplay amount={total} method={payMethod}/>}',
        '          {payMethod === ' + chr(39) + 'efectivo' + chr(39) + ' && (',
        '            <div className=' + chr(34) + 'bg-amber-50 border border-amber-200 rounded-xl p-4 text-center' + chr(34) + '>',
        '              <p className=' + chr(34) + 'text-amber-700 font-semibold' + chr(34) + '>Dirígete a la ventanilla de {schedule.company}</p>',
        '              <p className=' + chr(34) + 'text-3xl font-bold text-amber-700 mt-2' + chr(34) + '>Bs. {total.toFixed(2)}</p>',
        '              <p className=' + chr(34) + 'text-xs text-amber-600 mt-1' + chr(34) + '>Ref: BOL-{booking.id.slice(0,8).toUpperCase()}</p>',
        '            </div>',
        '          )}',
        '          {payMethod && (',
        '            <button onClick={handlePay} disabled={paying} className=' + chr(34) + 'w-full mt-4 bg-[#1B2A6B] hover:bg-[#162259] text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2' + chr(34) + '>',
        '              {paying ? ' + chr(39) + 'Verificando pago...' + chr(39) + ' : ' + chr(39) + '✅ Confirmar Pago' + chr(39) + '}',
        '            </button>',
        '          )}',
        '        </div>',
        '      )}',
        '',
        '      {step === 3 && (',
        '        <div className=' + chr(34) + 'card text-center' + chr(34) + '>',
        '          <CheckCircle size={64} className=' + chr(34) + 'text-green-500 mx-auto mb-4' + chr(34) + '/>',
        '          <h2 className=' + chr(34) + 'text-2xl font-bold text-[#1B2A6B] mb-2' + chr(34) + '>¡Pago Confirmado!</h2>',
        '          <p className=' + chr(34) + 'text-gray-600 mb-6' + chr(34) + '>Tu pasaje ha sido generado exitosamente</p>',
        '          <div className=' + chr(34) + 'bg-[#f0f4ff] rounded-xl p-4 text-left mb-6' + chr(34) + '>',
        '            <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Pasajero</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>{form.passenger_name}</span></div>',
        '            <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Ruta</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>{schedule.origin} → {schedule.destination}</span></div>',
        '            <div className=' + chr(34) + 'flex justify-between py-2 border-b border-gray-200' + chr(34) + '><span className=' + chr(34) + 'text-gray-600' + chr(34) + '>Asiento</span><span className=' + chr(34) + 'font-semibold' + chr(34) + '>{seat.seat_number} Piso {seat.floor}</span></div>',
        '            <div className=' + chr(34) + 'flex justify-between py-2' + chr(34) + '><span className=' + chr(34) + 'font-bold text-[#1B2A6B]' + chr(34) + '>TOTAL PAGADO</span><span className=' + chr(34) + 'font-bold text-[#1B2A6B] text-lg' + chr(34) + '>Bs. {total.toFixed(2)}</span></div>',
        '          </div>',
        '          <button onClick={handleDownload} className=' + chr(34) + 'w-full bg-[#1B2A6B] hover:bg-[#162259] text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2' + chr(34) + '>',
        '            <Download size={18}/> Descargar Ticket PDF',
        '          </button>',
        '        </div>',
        '      )}',
        '    </div>',
        '  );',
        '}',
    ]) + '\n')
print('OK: Checkout.jsx actualizado')