with open('vite.config.js', 'w', encoding='utf-8') as f:
    lines = [
        'import { defineConfig } from ' + chr(39) + 'vite' + chr(39) + ';',
        'import react from ' + chr(39) + '@vitejs/plugin-react' + chr(39) + ';',
        'import { VitePWA } from ' + chr(39) + 'vite-plugin-pwa' + chr(39) + ';',
        '',
        'export default defineConfig({',
        '  plugins: [',
        '    react(),',
        '    VitePWA({',
        '      registerType: ' + chr(39) + 'autoUpdate' + chr(39) + ',',
        '      manifest: {',
        '        name: ' + chr(39) + 'Bolivia Bus — Compra tu Pasaje' + chr(39) + ',',
        '        short_name: ' + chr(39) + 'Bolivia Bus' + chr(39) + ',',
        '        description: ' + chr(39) + 'Sistema de venta de pasajes interdepartamental de Bolivia' + chr(39) + ',',
        '        theme_color: ' + chr(39) + '#1B2A6B' + chr(39) + ',',
        '        background_color: ' + chr(39) + '#ffffff' + chr(39) + ',',
        '        display: ' + chr(39) + 'standalone' + chr(39) + ',',
        '        orientation: ' + chr(39) + 'portrait' + chr(39) + ',',
        '        start_url: ' + chr(39) + '/' + chr(39) + ',',
        '        icons: [',
        '          { src: ' + chr(39) + '/icon-192.png' + chr(39) + ', sizes: ' + chr(39) + '192x192' + chr(39) + ', type: ' + chr(39) + 'image/png' + chr(39) + ' },',
        '          { src: ' + chr(39) + '/icon-512.png' + chr(39) + ', sizes: ' + chr(39) + '512x512' + chr(39) + ', type: ' + chr(39) + 'image/png' + chr(39) + ' },',
        '        ],',
        '      },',
        '      workbox: {',
        '        runtimeCaching: [{',
        '          urlPattern: /^https:\/\/api\.boliviabus\.bo\/.*/i,',
        '          handler: ' + chr(39) + 'NetworkFirst' + chr(39) + ',',
        '          options: { cacheName: ' + chr(39) + 'api-cache' + chr(39) + ', expiration: { maxEntries: 50, maxAgeSeconds: 300 } }',
        '        }]',
        '      }',
        '    })',
        '  ]',
        '});',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: vite.config.js PWA')