with open('src/components/SearchHero.jsx', 'w', encoding='utf-8') as f:
    lines = [
        'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';',
        'import { motion, AnimatePresence } from ' + chr(39) + 'framer-motion' + chr(39) + ';',
        'import { MapPin, Calendar, Search, ArrowRight, ArrowLeftRight } from ' + chr(39) + 'lucide-react' + chr(39) + ';',
        'import { getDepartamentos, searchRoutes } from ' + chr(39) + '../api' + chr(39) + ';',
        '',
        'const DEPTO_FLAGS = {',
        '  "La Paz": "🏔️", "Santa Cruz": "🌴", "Cochabamba": "🌸",',
        '  "Oruro": "🎭", "Potosi": "⛏️", "Sucre": "🏛️", "Tarija": "🍇"',
        '};',
        '',
        'const BG_IMAGES = [',
        '  "https://images.unsplash.com/photo-1580048915913-4f8f5cb481c4?w=1920&q=80",',
        '  "https://images.unsplash.com/photo-1591604129939-f1efa4d9f7fa?w=1920&q=80",',
        '  "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=1920&q=80",',
        '];',
        '',
        'export default function SearchHero({ onResults }) {',
        '  const [departamentos, setDepartamentos] = useState([]);',
        '  const [form, setForm] = useState({ origin: "", destination: "", date: "", passengers: 1, tripType: "one_way" });',
        '  const [loading, setLoading] = useState(false);',
        '  const [error, setError] = useState("");',
        '  const [bgIdx, setBgIdx] = useState(0);',
        '',
        '  useEffect(() => {',
        '    getDepartamentos().then(r => setDepartamentos(r.data.departamentos)).catch(() => {});',
        '    const today = new Date().toISOString().split("T")[0];',
        '    setForm(f => ({ ...f, date: today }));',
        '    const interval = setInterval(() => setBgIdx(i => (i + 1) % BG_IMAGES.length), 5000);',
        '    return () => clearInterval(interval);',
        '  }, []);',
        '',
        '  const swapLocations = () => setForm(f => ({ ...f, origin: f.destination, destination: f.origin }));',
        '',
        '  const handleSearch = async (e) => {',
        '    e.preventDefault();',
        '    if (!form.origin || !form.destination || !form.date) { setError("Completa todos los campos"); return; }',
        '    if (form.origin === form.destination) { setError("Origen y destino deben ser diferentes"); return; }',
        '    setLoading(true); setError("");',
        '    try {',
        '      const res = await searchRoutes(form);',
        '      onResults(res.data.results, form);',
        '    } catch { setError("Error al buscar."); }',
        '    finally { setLoading(false); }',
        '  };',
        '',
        '  return (',
        '    <div className="relative min-h-[520px] flex flex-col items-center justify-center px-4 py-12 overflow-hidden">',
        '      <AnimatePresence mode="wait">',
        '        <motion.div key={bgIdx} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} transition={{ duration: 1.5 }}',
        '          className="absolute inset-0 bg-cover bg-center"',
        '          style={{ backgroundImage: "url(" + BG_IMAGES[bgIdx] + ")" }}/>',
        '      </AnimatePresence>',
        '      <div className="absolute inset-0 bg-gradient-to-b from-[#1B2A6B]/80 via-[#1B2A6B]/70 to-[#0d1a4a]/90"/>',
        '      <div className="relative z-10 text-center mb-8">',
        '        <motion.div initial={{ opacity:0, y:-30 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8 }}>',
        '          <h1 className="text-5xl md:text-6xl font-black text-white mb-3 tracking-tight">',
        '            Bolivia <span className="text-[#D4AF37]">Bus</span>',
        '          </h1>',
        '          <p className="text-blue-200 text-lg">Viaja seguro por los 7 departamentos de Bolivia</p>',
        '        </motion.div>',
        '      </div>',
        '      <motion.div initial={{ opacity:0, y:30 }} animate={{ opacity:1, y:0 }} transition={{ duration:0.8, delay:0.2 }}',
        '        className="relative z-10 bg-white/95 backdrop-blur-md rounded-2xl shadow-2xl p-6 w-full max-w-4xl">',
        '        <div className="flex gap-3 mb-5">',
        '          {[{id:"one_way",label:"Solo Ida"},{id:"round_trip",label:"Ida y Vuelta"}].map(t => (',
        '            <button key={t.id} onClick={() => setForm({...form, tripType: t.id})}',
        '              className={"px-4 py-2 rounded-full text-sm font-semibold transition-all " + (form.tripType === t.id ? "bg-[#1B2A6B] text-white" : "bg-gray-100 text-gray-600")}>',
        '              {t.label}',
        '            </button>',
        '          ))}',
        '        </div>',
        '        <form onSubmit={handleSearch}>',
        '          <div className="grid grid-cols-1 md:grid-cols-9 gap-3 items-end">',
        '            <div className="md:col-span-3 flex flex-col gap-1">',
        '              <label className="text-xs font-bold text-gray-500 uppercase">🗺️ Origen</label>',
        '              <select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})}',
        '                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-[#1B2A6B] bg-gray-50 font-medium">',
        '                <option value="">Desde donde?</option>',
        '                {departamentos.map(d => <option key={d} value={d}>{DEPTO_FLAGS[d]} {d}</option>)}',
        '              </select>',
        '            </div>',
        '            <div className="md:col-span-1 flex justify-center">',
        '              <button type="button" onClick={swapLocations}',
        '                className="w-10 h-10 rounded-full bg-[#1B2A6B] text-white flex items-center justify-center hover:bg-[#D4AF37] transition-all mt-4">',
        '                <ArrowLeftRight size={16}/>',
        '              </button>',
        '            </div>',
        '            <div className="md:col-span-3 flex flex-col gap-1">',
        '              <label className="text-xs font-bold text-gray-500 uppercase">📍 Destino</label>',
        '              <select value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}',
        '                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-[#1B2A6B] bg-gray-50 font-medium">',
        '                <option value="">A donde vas?</option>',
        '                {departamentos.map(d => <option key={d} value={d}>{DEPTO_FLAGS[d]} {d}</option>)}',
        '              </select>',
        '            </div>',
        '            <div className="md:col-span-2 flex flex-col gap-1">',
        '              <label className="text-xs font-bold text-gray-500 uppercase">📅 Fecha</label>',
        '              <input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}',
        '                className="w-full px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-[#1B2A6B] bg-gray-50 font-medium"/>',
        '            </div>',
        '          </div>',
        '          {form.tripType === "round_trip" && (',
        '            <div className="mt-3 flex flex-col gap-1">',
        '              <label className="text-xs font-bold text-gray-500 uppercase">📅 Fecha Regreso</label>',
        '              <input type="date" value={form.return_date || ""} onChange={e=>setForm({...form,return_date:e.target.value})}',
        '                className="w-full md:w-48 px-4 py-3 border-2 border-gray-200 rounded-xl focus:outline-none focus:border-[#1B2A6B] bg-gray-50"/>',
        '            </div>',
        '          )}',
        '          {error && <p className="text-red-500 text-sm mt-3 text-center font-medium">{error}</p>}',
        '          <motion.button type="submit" disabled={loading}',
        '            whileHover={{ scale: 1.02 }} whileTap={{ scale: 0.98 }}',
        '            className="w-full mt-4 bg-gradient-to-r from-[#1B2A6B] to-[#2d45a8] text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 text-lg shadow-lg">',
        '            {loading ? (',
        '              <><div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"/><span>Buscando...</span></>',
        '            ) : (',
        '              <><Search size={20}/><span>Buscar Pasajes</span><ArrowRight size={20}/></>',
        '            )}',
        '          </motion.button>',
        '        </form>',
        '      </motion.div>',
        '      <div className="relative z-10 flex gap-6 mt-6 text-white/70 text-sm">',
        '        <span>✅ Pago seguro</span>',
        '        <span>🎫 Ticket digital</span>',
        '        <span>🚌 11 rutas disponibles</span>',
        '      </div>',
        '    </div>',
        '  );',
        '}',
    ]
    f.write('\n'.join(lines) + '\n')
print('OK: SearchHero.jsx')