with open('src/App.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import SearchHero from ' + chr(39) + './components/SearchHero' + chr(39) + ';\n'
'import SearchResults from ' + chr(39) + './components/SearchResults' + chr(39) + ';\n'
'import SeatMap from ' + chr(39) + './components/SeatMap' + chr(39) + ';\n'
'import Checkout from ' + chr(39) + './components/Checkout' + chr(39) + ';\n'
'\n'
'export default function App() {\n'
'  const [step, setStep] = useState(' + chr(39) + 'search' + chr(39) + ');\n'
'  const [results, setResults] = useState(null);\n'
'  const [searchInfo, setSearchInfo] = useState(null);\n'
'  const [selectedSchedule, setSelectedSchedule] = useState(null);\n'
'  const [selectedSeat, setSelectedSeat] = useState(null);\n'
'\n'
'  const handleResults = (data, info) => { setResults(data); setSearchInfo(info); setStep(' + chr(39) + 'results' + chr(39) + '); };\n'
'  const handleSelectSchedule = (s) => { setSelectedSchedule(s); setStep(' + chr(39) + 'seats' + chr(39) + '); };\n'
'  const handleSelectSeat = (seat) => { setSelectedSeat(seat); };\n'
'  const handleCheckout = () => { if (selectedSeat) setStep(' + chr(39) + 'checkout' + chr(39) + '); };\n'
'  const handleBack = () => setStep(step === ' + chr(39) + 'checkout' + chr(39) + ' ? ' + chr(39) + 'seats' + chr(39) + ' : step === ' + chr(39) + 'seats' + chr(39) + ' ? ' + chr(39) + 'results' + chr(39) + ' : ' + chr(39) + 'search' + chr(39) + ');\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'min-h-screen bg-gray-50' + chr(34) + '>\n'
'      <SearchHero onResults={handleResults}/>\n'
'      {step === ' + chr(39) + 'results' + chr(39) + ' && <SearchResults results={results} searchInfo={searchInfo} onSelect={handleSelectSchedule}/>}\n'
'      {step === ' + chr(39) + 'seats' + chr(39) + ' && (\n'
'        <div className=' + chr(34) + 'max-w-4xl mx-auto px-4 py-8' + chr(34) + '>\n'
'          <button onClick={handleBack} className=' + chr(34) + 'text-[#1B2A6B] mb-4 flex items-center gap-1 hover:underline' + chr(34) + '>← Volver a resultados</button>\n'
'          <SeatMap schedule={selectedSchedule} onSeatSelected={handleSelectSeat}/>\n'
'          {selectedSeat && (\n'
'            <div className=' + chr(34) + 'text-center mt-6' + chr(34) + '>\n'
'              <button onClick={handleCheckout} className=' + chr(34) + 'btn-primary px-12' + chr(34) + '>Continuar al pago →</button>\n'
'            </div>\n'
'          )}\n'
'        </div>\n'
'      )}\n'
'      {step === ' + chr(39) + 'checkout' + chr(39) + ' && <Checkout schedule={selectedSchedule} seat={selectedSeat} onBack={handleBack}/>}\n'
'      <footer className=' + chr(34) + 'bg-[#1B2A6B] text-white text-center py-6 mt-12 text-sm' + chr(34) + '>\n'
'        <p>Bolivia Bus © 2026 | Sistema Integral de Ticketing Terrestre</p>\n'
'        <p className=' + chr(34) + 'text-[#D4AF37] mt-1' + chr(34) + '>La Paz · Cochabamba · Santa Cruz · Oruro · Potosí · Sucre · Tarija</p>\n'
'      </footer>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: App.jsx')