with open('src/components/SearchHero.jsx', 'w', encoding='utf-8') as f:
    f.write(
'import { useState, useEffect } from ' + chr(39) + 'react' + chr(39) + ';\n'
'import { MapPin, Calendar, Users, Search, ArrowRight } from ' + chr(39) + 'lucide-react' + chr(39) + ';\n'
'import { getDepartamentos, searchRoutes } from ' + chr(39) + '../api' + chr(39) + ';\n'
'\n'
'export default function SearchHero({ onResults }) {\n'
'  const [departamentos, setDepartamentos] = useState([]);\n'
'  const [form, setForm] = useState({ origin: ' + chr(39) + chr(39) + ', destination: ' + chr(39) + chr(39) + ', date: ' + chr(39) + chr(39) + ', passengers: 1 });\n'
'  const [loading, setLoading] = useState(false);\n'
'  const [error, setError] = useState(' + chr(39) + chr(39) + ');\n'
'\n'
'  useEffect(() => {\n'
'    getDepartamentos().then(r => setDepartamentos(r.data.departamentos)).catch(() => {});\n'
'    const today = new Date().toISOString().split(' + chr(39) + 'T' + chr(39) + ')[0];\n'
'    setForm(f => ({ ...f, date: today }));\n'
'  }, []);\n'
'\n'
'  const handleSearch = async (e) => {\n'
'    e.preventDefault();\n'
'    if (!form.origin || !form.destination || !form.date) { setError(' + chr(39) + 'Completa todos los campos' + chr(39) + '); return; }\n'
'    if (form.origin === form.destination) { setError(' + chr(39) + 'Origen y destino deben ser diferentes' + chr(39) + '); return; }\n'
'    setLoading(true); setError(' + chr(39) + chr(39) + ');\n'
'    try {\n'
'      const res = await searchRoutes(form);\n'
'      onResults(res.data.results, form);\n'
'    } catch { setError(' + chr(39) + 'Error al buscar. Intenta nuevamente.' + chr(39) + '); }\n'
'    finally { setLoading(false); }\n'
'  };\n'
'\n'
'  return (\n'
'    <div className=' + chr(34) + 'bg-gradient-to-br from-[#1B2A6B] to-[#0d1a4a] min-h-[420px] flex flex-col items-center justify-center px-4 py-12' + chr(34) + '>\n'
'      <div className=' + chr(34) + 'text-center mb-8' + chr(34) + '>\n'
'        <h1 className=' + chr(34) + 'text-4xl md:text-5xl font-bold text-white mb-2' + chr(34) + '>Bolivia <span className=' + chr(34) + 'text-[#D4AF37]' + chr(34) + '>Bus</span></h1>\n'
'        <p className=' + chr(34) + 'text-blue-200 text-lg' + chr(34) + '>Viaja por los 7 departamentos de Bolivia</p>\n'
'      </div>\n'
'      <form onSubmit={handleSearch} className=' + chr(34) + 'bg-white rounded-2xl shadow-2xl p-6 w-full max-w-4xl' + chr(34) + '>\n'
'        <div className=' + chr(34) + 'grid grid-cols-1 md:grid-cols-4 gap-4' + chr(34) + '>\n'
'          <div className=' + chr(34) + 'flex flex-col gap-1' + chr(34) + '>\n'
'            <label className=' + chr(34) + 'text-xs font-semibold text-gray-500 uppercase flex items-center gap-1' + chr(34) + '><MapPin size={12}/> Origen</label>\n'
'            <select value={form.origin} onChange={e=>setForm({...form,origin:e.target.value})} className=' + chr(34) + 'input-field bg-gray-50' + chr(34) + '>\n'
'              <option value=' + chr(34) + chr(34) + '>Seleccionar...</option>\n'
'              {departamentos.map(d=><option key={d} value={d}>{d}</option>)}\n'
'            </select>\n'
'          </div>\n'
'          <div className=' + chr(34) + 'flex flex-col gap-1' + chr(34) + '>\n'
'            <label className=' + chr(34) + 'text-xs font-semibold text-gray-500 uppercase flex items-center gap-1' + chr(34) + '><MapPin size={12}/> Destino</label>\n'
'            <select value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})} className=' + chr(34) + 'input-field bg-gray-50' + chr(34) + '>\n'
'              <option value=' + chr(34) + chr(34) + '>Seleccionar...</option>\n'
'              {departamentos.map(d=><option key={d} value={d}>{d}</option>)}\n'
'            </select>\n'
'          </div>\n'
'          <div className=' + chr(34) + 'flex flex-col gap-1' + chr(34) + '>\n'
'            <label className=' + chr(34) + 'text-xs font-semibold text-gray-500 uppercase flex items-center gap-1' + chr(34) + '><Calendar size={12}/> Fecha</label>\n'
'            <input type=' + chr(34) + 'date' + chr(34) + ' value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className=' + chr(34) + 'input-field bg-gray-50' + chr(34) + '/>\n'
'          </div>\n'
'          <div className=' + chr(34) + 'flex flex-col gap-1' + chr(34) + '>\n'
'            <label className=' + chr(34) + 'text-xs font-semibold text-gray-500 uppercase flex items-center gap-1' + chr(34) + '><Users size={12}/> Pasajeros</label>\n'
'            <select value={form.passengers} onChange={e=>setForm({...form,passengers:+e.target.value})} className=' + chr(34) + 'input-field bg-gray-50' + chr(34) + '>\n'
'              {[1,2,3,4,5].map(n=><option key={n} value={n}>{n} pasajero{n>1?' + chr(34) + 's' + chr(34) + ':' + chr(34) + chr(34) + '}</option>)}\n'
'            </select>\n'
'          </div>\n'
'        </div>\n'
'        {error && <p className=' + chr(34) + 'text-red-500 text-sm mt-3 text-center' + chr(34) + '>{error}</p>}\n'
'        <button type=' + chr(34) + 'submit' + chr(34) + ' disabled={loading} className=' + chr(34) + 'btn-primary w-full mt-4 flex items-center justify-center gap-2' + chr(34) + '>\n'
'          {loading ? <span>Buscando...</span> : <><Search size={18}/> Buscar Pasajes <ArrowRight size={18}/></>}\n'
'        </button>\n'
'      </form>\n'
'    </div>\n'
'  );\n'
'}\n'
    )
print('OK: SearchHero.jsx')